### ISSUE TITLE
Error on antibody bundle

### ISSUE THREAD

**Issue by caarlos0** [getantibody/antibody#151]
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x12e002bac5da pc=0xe28b]

runtime stack:
runtime.throw(0x20ae20, 0x2a)
    /usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x2c7e60)
    /usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x2c7e60, 0x1, 0x2b, 0x31e960)
    /usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
    /usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc82005be58)
    /usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x2c7e60, 0x1, 0x1000000002b, 0xdf2f)
    /usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x2ca400, 0x0)
    /usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x2ca400, 0xc8200d0170)
    /usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x31e960, 0xc80000002b, 0xc8200bcb38)
    /usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
    /usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc82001aa00)
    /usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
    /usr/local/go/src/runtime/proc.go:1051

goroutine 14 [running]:
runtime.systemstack_switch()
    /usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc8200bc898 sp=0xc8200bc890
runtime.mallocgc(0x1000, 0x14d700, 0x1, 0x158900)
    /usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc8200bc970 sp=0xc8200bc898
runtime.newarray(0x14d700, 0x1000, 0x300000001)
    /usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc8200bc9b0 sp=0xc8200bc970
runtime.makeslice(0x1455e0, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc8200bca00 sp=0xc8200bc9b0
os.(*File).readdirnames(0xc8200fe000, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/os/dir_unix.go:23 +0xc7 fp=0xc8200bcaf0 sp=0xc8200bca00
os.(*File).Readdirnames(0xc8200fe000, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/os/doc.go:138 +0x85 fp=0xc8200bcb30 sp=0xc8200bcaf0
path/filepath.glob(0xc8200ec100, 0x66, 0xc8200ec167, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/path/filepath/match.go:289 +0x1d2 fp=0xc8200bcc50 sp=0xc8200bcb30
path/filepath.Glob(0xc8200ec100, 0x73, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/path/filepath/match.go:253 +0x282 fp=0xc8200bcd40 sp=0xc8200bcc50
github.com/getantibody/antibody/bundle.zshBundle.Get(0x3723d8, 0xc8200cc210, 0x0, 0x0, 0x0, 0x0)
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/bundle/zsh.go:20 +0x24f fp=0xc8200bce60 sp=0xc8200bcd40
github.com/getantibody/antibody/bundle.(*zshBundle).Get(0xc8200c4050, 0x0, 0x0, 0x0, 0x0)
    <autogenerated>:3 +0xb4 fp=0xc8200bce98 sp=0xc8200bce60
github.com/getantibody/antibody.(*Antibody).Bundle.func1(0x0, 0x0)
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/antibody.go:40 +0x137 fp=0xc8200bcf50 sp=0xc8200bce98
github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc82000e680, 0xc8200148d0)
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x5a fp=0xc8200bcfa0 sp=0xc8200bcf50
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200bcfa8 sp=0xc8200bcfa0
created by github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup.(*Group).Go
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup/errgroup.go:66 +0x62

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc82000e694)
    /usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc82000e688)
    /usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup.(*Group).Wait(0xc82000e680, 0x0, 0x0)
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup/errgroup.go:41 +0x39
github.com/getantibody/antibody.(*Antibody).Bundle(0xc82000a8c0, 0x0, 0x0, 0x0, 0x0)
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/antibody.go:52 +0x3d7
github.com/getantibody/antibody/cmd/antibody/command.doBundle(0xc820096140, 0x0, 0x0)
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/cmd/antibody/command/bundle.go:29 +0x1d5
reflect.Value.call(0x156ba0, 0x21d660, 0x13, 0x1cd230, 0x4, 0xc82009f508, 0x1, 0x1, 0x0, 0x0, ...)
    /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x156ba0, 0x21d660, 0x13, 0xc82009f508, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/getantibody/antibody/vendor/github.com/urfave/cli.HandleAction(0x156ba0, 0x21d660, 0xc820096140, 0x0, 0x0)
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/github.com/urfave/cli/app.go:487 +0x2ee
github.com/getantibody/antibody/vendor/github.com/urfave/cli.Command.Run(0x1ce450, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20b7e0, 0x33, 0x0, ...)
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/github.com/urfave/cli/command.go:191 +0xfec
github.com/getantibody/antibody/vendor/github.com/urfave/cli.(*App).Run(0xc820000d80, 0xc82000a2a0, 0x2, 0x2, 0x0, 0x0)
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/cmd/antibody/main.go:25 +0x1e7

goroutine 13 [runnable]:
syscall.Syscall6(0x158, 0x4, 0xc8200f3000, 0x1000, 0xc8200b89f0, 0x0, 0x0, 0x140, 0x0, 0x0)
    /usr/local/go/src/syscall/asm_darwin_amd64.s:41 +0x5
syscall.Getdirentries(0x4, 0xc8200f3000, 0x1000, 0x1000, 0xc8200b89f0, 0x0, 0x0, 0x0)
    /usr/local/go/src/syscall/zsyscall_darwin_amd64.go:571 +0x91
syscall.ReadDirent(0x4, 0xc8200f3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/syscall/syscall_bsd.go:71 +0x63
os.(*File).readdirnames(0xc8200ee008, 0xffffffffffffffff, 0xc8200f6680, 0x0, 0x64, 0x0, 0x0)
    /usr/local/go/src/os/dir_unix.go:39 +0x215
os.(*File).Readdirnames(0xc8200ee008, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/os/doc.go:138 +0x85
path/filepath.glob(0xc8200e6380, 0x69, 0xc8200e63ea, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/path/filepath/match.go:289 +0x1d2
path/filepath.Glob(0xc8200e6380, 0x76, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/path/filepath/match.go:253 +0x282
github.com/getantibody/antibody/bundle.zshBundle.Get(0x3723d8, 0xc8200ce240, 0x0, 0x0, 0x0, 0x0)
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/bundle/zsh.go:20 +0x24f
github.com/getantibody/antibody/bundle.(*zshBundle).Get(0xc8200c80c0, 0x0, 0x0, 0x0, 0x0)
    <autogenerated>:3 +0xb4
github.com/getantibody/antibody.(*Antibody).Bundle.func1(0x0, 0x0)
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/antibody.go:40 +0x137
github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc82000e680, 0xc8200148a0)
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x5a
created by github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup.(*Group).Go
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup/errgroup.go:66 +0x62

goroutine 15 [running]:
    goroutine running on other thread; stack unavailable
created by github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup.(*Group).Go
    /home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup/errgroup.go:66 +0x62
./antibody/install.sh: line 11: 11268 Segmentation fault: 11  antibody bundle sindresorhus/pure >> ~/.bundles.txt
```

antibody version v2.1.0

**Comment by ahmedre** [comment]
thanks for writing `antibody`!

i run into a segmentation fault when i open a new terminal  (not very often, but sometimes - maybe one in every ten or twenty times).

i was able to repro a little more consistently by running this a few times:

`for i in $(seq 1 10); do /usr/bin/time zsh -i -c exit; done`

**Comment by caarlos0** [comment]
@ahmedre I need to spend some time on this... Will try to tackle it today

**Comment by caarlos0** [comment]
@ahmedre can you paste some logs of the errors you get and your `uname -a` (just for sanity check) ?

**Comment by ahmedre** [comment]
the trace i got yesterday were exactly the same trace that you had here - i haven't been able to get it again today (oddly enough, the one or two times things did fail, i just got "Segmentation Fault" and didn't get the trace this time). i also tried to enable coredumps in OS X, which ended up being a bad idea (it dumped an 85gb core file!) can you tell me how to force it to give me the stack trace again?

`uname -a` output:

```
Darwin Ahmeds-iMac.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
```

**Comment by caarlos0** [comment]
@ahmedre thanks, well, I tried to reproduce the error several times and I couldn't...

Will try again later today... 

I don't know how to dump the stack trace... 

The version distributed via homebrew et al is without the debug symbols, which makes the entire process more difficult.

If you want, I built a version with all symbols (`-no-strip`): https://github.com/getantibody/antibody/releases/download/v2.1.2/antibody-no-strip-test-only-darwin-x64

You can try to reproduce the error on this version and it should give you the entire stack trace (I'm using this version here too to see if it happens).

Thanks

**Comment by ahmedre** [comment]
tried it today, but unfortunately can't get the crash - tried many runs with `seq 1 100` and still no crash :( i'll let you know if i run into it again though.

**Comment by ahmedre** [comment]
spoke too soon - was trying to figure out what has been taking time for startup, so modified one of my configs and ran a for loop with 10 times (without the symbolicated one) - and this time i did get the trace:

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x1d5b9d71112c pc=0xe28b]

runtime stack:
runtime.throw(0x20b420, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x2c7e60)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x2c7e60, 0x1, 0x3, 0x3243a0)
	/usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc820039e58)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x2c7e60, 0x1, 0x10000000003, 0xdf2f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x2c9280, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x2c9280, 0x3243a0)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x31e4b0, 0xc800000003, 0x3243a0)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820019500)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 7 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc8200ca918 sp=0xc8200ca910
runtime.mallocgc(0x20, 0x19d1a0, 0x0, 0xc8200fe000)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc8200ca9f0 sp=0xc8200ca918
runtime.newobject(0x19d1a0, 0xc8200fe000)
	/usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0xc8200caa18 sp=0xc8200ca9f0
os.NewFile(0x3, 0xc8200ec200, 0x71, 0xe00000000)
	/usr/local/go/src/os/file_unix.go:56 +0x5f fp=0xc8200caa70 sp=0xc8200caa18
os.OpenFile(0xc8200ec200, 0x71, 0x0, 0xc800000000, 0xc8200fc0d0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:123 +0x1c9 fp=0xc8200caaf0 sp=0xc8200caa70
os.Open(0xc8200ec200, 0x71, 0x372210, 0x0, 0x0)
	/usr/local/go/src/os/file.go:244 +0x48 fp=0xc8200cab30 sp=0xc8200caaf0
path/filepath.glob(0xc8200ec200, 0x71, 0xc8200ec272, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/path/filepath/match.go:283 +0x15d fp=0xc8200cac50 sp=0xc8200cab30
path/filepath.Glob(0xc8200ec200, 0x7e, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/path/filepath/match.go:253 +0x282 fp=0xc8200cad40 sp=0xc8200cac50
github.com/getantibody/antibody/bundle.zshBundle.Get(0x3723d8, 0xc8200de030, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/bundle/zsh.go:20 +0x24f fp=0xc8200cae60 sp=0xc8200cad40
github.com/getantibody/antibody/bundle.(*zshBundle).Get(0xc8200c2020, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:4 +0xb4 fp=0xc8200cae98 sp=0xc8200cae60
github.com/getantibody/antibody.(*Antibody).Bundle.func1(0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/antibody.go:40 +0x137 fp=0xc8200caf50 sp=0xc8200cae98
github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc82000e4c0, 0xc8200166c0)
	/home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x5a fp=0xc8200cafa0 sp=0xc8200caf50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200cafa8 sp=0xc8200cafa0
created by github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup/errgroup.go:66 +0x62

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc82000e4d4)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc82000e4c8)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup.(*Group).Wait(0xc82000e4c0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/golang.org/x/sync/errgroup/errgroup.go:41 +0x39
github.com/getantibody/antibody.(*Antibody).Bundle(0xc82000a820, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/antibody.go:52 +0x3d7
github.com/getantibody/antibody/cmd/antibody/command.doBundle(0xc820094140, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/cmd/antibody/command/bundle.go:29 +0x1d5
reflect.Value.call(0x156da0, 0x21dc60, 0x13, 0x1cd6f0, 0x4, 0xc82009d508, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x156da0, 0x21dc60, 0x13, 0xc82009d508, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/getantibody/antibody/vendor/github.com/urfave/cli.HandleAction(0x156da0, 0x21dc60, 0xc820094140, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/github.com/urfave/cli/app.go:487 +0x2ee
github.com/getantibody/antibody/vendor/github.com/urfave/cli.Command.Run(0x1ce910, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20bde0, 0x33, 0x0, ...)
	/home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/github.com/urfave/cli/command.go:191 +0xfec
github.com/getantibody/antibody/vendor/github.com/urfave/cli.(*App).Run(0xc820001080, 0xc82000a2c0, 0x2, 0x2, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/vendor/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/home/ubuntu/.go_workspace/src/github.com/getantibody/antibody/cmd/antibody/main.go:25 +0x1e7
```

not sure where `/home/ubuntu` is coming from, i'm on a mac.

**Comment by caarlos0** [comment]
@ahmedre it's the home folder that the machine that compiled the binary used... don't worry about it.

It seems like some issue in the golang file glob code... I'll try to create a build in a newer Go version.

If the issue persists, I'll open an issue in go's repo.

**Comment by caarlos0** [comment]
@ahmedre done, can you use the new version? https://github.com/getantibody/antibody/releases/tag/v2.2.0

I'll push it to homebrew in a sec

**Comment by caarlos0** [comment]
just pushed

**Comment by ahmedre** [comment]
haven't been able to repro up until now - will update if i do repro though, thank you!

**Comment by caarlos0** [comment]
@ahmedre NICE =D

Thanks! I'll close this next week then 👍 

Thanks for all the help!

**Comment by caarlos0** [comment]
Seems to be OK now, so, closing...

**Comment by ahmedre** [comment]
awesome, thanks for fixing this!
